FROM python:3.11.4-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "movie.src.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
